global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['172.17.0.1:9090']
    basic_auth:
      username: 'admin'
      password: '12345678'
  - job_name: 'node-exporter'
    scrape_interval: 1m
    static_configs:
      - targets: ['172.17.0.1:9100']
    basic_auth:
      username: 'admin'
      password: '12345678'
  - job_name: 'spring-actuator'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.17.0.1:8080']
    basic_auth:
      username: 'prometheus'
      password: 'prometheus'
  - job_name: alertmanager
    static_configs:
      - targets: ['172.17.0.1:9093']

rule_files:
  - alert.yml

alerting:
  alertmanagers:
  - static_configs:
      - targets: [ '172.17.0.1:9093' ]
